---
- name: Create ansible user with root privileges
  hosts: my_hosts
  become: true
  gather_facts: false

  vars:
    ansible_client_username: username
    ansible_client_password: pwd

  tasks:
    - name: Create ansible user with password
      user:
        name: "{{ ansible_client_username }}"
        password: "{{ ansible_client_password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes

    - name: Grant ansible user sudo privileges
      copy:
        dest: "/etc/sudoers.d/{{ ansible_client_username }}"
        content: "{{ ansible_client_username }} ALL=(ALL) ALL"
        owner: root
        group: root
        mode: '0440'
