---
- name: Configure APT proxy
  hosts: gepeim
  become: true
  tasks:
    - name: Set apt proxy
      copy:
        dest: /etc/apt/apt.conf.d/01proxy
        content: 'Acquire::http::Proxy "http://192.168.2.207:3142";'
        owner: root
        group: root
        mode: '0644'
        force: yes
